data<-read.table("household_power_consumption.txt",sep=";",dec=".",header=T,stringsAsFactors =F )
datasub<-subset(data,data$Date=="1/2/2007"|data$Date=="2/2/2007")
datatime<-strptime(paste(datasub$Date,datasub$Time),"%d/%m/%Y %H:%M:%S")
sub1<-as.numeric(datasub$Sub_metering_1)
sub2<-as.numeric(datasub$Sub_metering_2)
sub3<-as.numeric(datasub$Sub_metering_3)
png("plot3.png",width=480,height = 480)
plot(datatime,sub1,type="l",ylab="Energy Submetering", xlab="")
lines(datatime,sub2,type="l",col="red")
lines(datatime,sub3,type="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
